from pathlib import Path
import itertools

import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    balanced_accuracy_score,
    f1_score,
    precision_score,
    recall_score,
)
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.pipeline import Pipeline


ROOT = Path(__file__).resolve().parents[2]

DATA_FILE = (
    ROOT
    / "data"
    / "training"
    / "theefinder_verified_ml_features.csv"
)

OUTPUT_FILE = (
    ROOT
    / "data"
    / "training"
    / "stage_b_quick_tuning_results.csv"
)


RANDOM_STATE = 42
N_SPLITS = 5


# ============================================================
# CURRENT PRODUCTION STAGE-B FEATURES
# ============================================================

BASE_FEATURES = [
    "frp",
    "confidence_score",
    "confidence_available",
    "is_daytime",
    "daynight_available",
    "distance_to_industry_m",
    "industry_distance_available",
    "industrial_proximity_score",
    "industrial_feature_count_5km",
    "tree_cover_pct",
    "shrubland_pct",
    "grassland_pct",
    "cropland_pct",
    "built_up_pct",
    "bare_sparse_pct",
    "water_pct",
    "wetland_pct",
    "mangrove_pct",
    "detections_30d",
    "active_days_30d",
    "persistence_score",
]


# ============================================================
# EXTRA FEATURES ALREADY GENERATED BY THEEFINDER
# ============================================================

HISTORY_CANDIDATES = [
    "historical_average_frp",
    "historical_maximum_frp",
    "historical_frp_std",
    "frp_ratio",
    "historical_satellite_count",
]


def create_pipeline(
    features,
    params,
):

    distance_columns = [
        "distance_to_industry_m"
    ]

    other_columns = [
        feature
        for feature in features
        if feature
        != "distance_to_industry_m"
    ]

    preprocessing = ColumnTransformer(
        transformers=[
            (
                "distance",
                SimpleImputer(
                    strategy="constant",
                    fill_value=6000.0,
                ),
                distance_columns,
            ),
            (
                "other",
                SimpleImputer(
                    strategy="median"
                ),
                other_columns,
            ),
        ],
        remainder="drop",
        verbose_feature_names_out=False,
    )

    classifier = RandomForestClassifier(
        n_estimators=600,

        max_depth=
            params["max_depth"],

        min_samples_leaf=
            params["min_samples_leaf"],

        max_features=
            params["max_features"],

        class_weight=
            params["class_weight"],

        random_state=
            RANDOM_STATE,

        n_jobs=-1,
    )

    return Pipeline(
        [
            (
                "preprocessor",
                preprocessing,
            ),
            (
                "classifier",
                classifier,
            ),
        ]
    )


# ============================================================
# LOAD STAGE-B DATA
# ============================================================

df = pd.read_csv(
    DATA_FILE
)

df = df[
    df["stage_a_label"]
    ==
    "INDUSTRIAL"
].copy()

print()
print("=" * 76)
print("THEEFINDER STAGE-B QUICK OPTIMIZER")
print("=" * 76)

print(
    f"\nIndustrial rows: {len(df)}"
)

print(
    f"Independent groups: "
    f"{df['group_id'].nunique()}"
)

print("\nClass counts:")

print(
    df["stage_b_label"]
    .value_counts()
    .to_string()
)


# ============================================================
# HISTORY FEATURE QUALITY
# ============================================================

usable_history = []

print()
print("=" * 76)
print("HISTORY FEATURE MISSINGNESS")
print("=" * 76)

for feature in HISTORY_CANDIDATES:

    if feature not in df.columns:

        print(
            f"{feature:30} "
            "NOT PRESENT"
        )

        continue

    missing = float(
        df[feature]
        .isna()
        .mean()
    )

    print(
        f"{feature:30} "
        f"{missing:.1%} missing"
    )

    # Keep only reasonably populated features.
    if missing <= 0.40:
        usable_history.append(
            feature
        )


feature_sets = {
    "BASE":
        BASE_FEATURES,
}

if usable_history:

    feature_sets[
        "BASE_PLUS_HISTORY"
    ] = (
        BASE_FEATURES
        +
        usable_history
    )


# ============================================================
# FAST PARAMETER GRID
# ============================================================

configs = []

for (
    max_depth,
    min_leaf,
    max_features,
    class_weight,
) in itertools.product(

    [3, 4, 5, None],

    [1, 2],

    [
        "sqrt",
    ],

    [
        "balanced",
        "balanced_subsample",

        {
            "INDUSTRIAL_FIRE": 2.0,
            "PERSISTENT_INDUSTRIAL_SOURCE": 1.0,
        },

        {
            "INDUSTRIAL_FIRE": 3.0,
            "PERSISTENT_INDUSTRIAL_SOURCE": 1.0,
        },
    ],
):

    configs.append(
        {
            "max_depth":
                max_depth,

            "min_samples_leaf":
                min_leaf,

            "max_features":
                max_features,

            "class_weight":
                class_weight,
        }
    )


cv = StratifiedGroupKFold(
    n_splits=N_SPLITS,
    shuffle=True,
    random_state=RANDOM_STATE,
)


all_results = []


# ============================================================
# CROSS-VALIDATED PROBABILITY TUNING
# ============================================================

for (
    feature_set_name,
    features,
) in feature_sets.items():

    X = df[
        features
    ].copy()

    for column in features:

        X[column] = pd.to_numeric(
            X[column],
            errors="coerce",
        )

    y = (
        df["stage_b_label"]
        .astype(str)
        .reset_index(drop=True)
    )

    groups = (
        df["group_id"]
        .astype(str)
        .reset_index(drop=True)
    )

    X = X.reset_index(
        drop=True
    )

    for (
        config_number,
        params,
    ) in enumerate(
        configs,
        start=1,
    ):

        actual = np.empty(
            len(df),
            dtype=object,
        )

        fire_probabilities = (
            np.zeros(
                len(df),
                dtype=float,
            )
        )

        for (
            train_index,
            test_index,
        ) in cv.split(
            X,
            y,
            groups,
        ):

            pipeline = (
                create_pipeline(
                    features,
                    params,
                )
            )

            pipeline.fit(
                X.iloc[
                    train_index
                ],
                y.iloc[
                    train_index
                ],
            )

            probabilities = (
                pipeline.predict_proba(
                    X.iloc[
                        test_index
                    ]
                )
            )

            classes = list(
                pipeline[
                    "classifier"
                ].classes_
            )

            fire_index = (
                classes.index(
                    "INDUSTRIAL_FIRE"
                )
            )

            fire_probabilities[
                test_index
            ] = (
                probabilities[
                    :,
                    fire_index
                ]
            )

            actual[
                test_index
            ] = (
                y.iloc[
                    test_index
                ].values
            )

        # ----------------------------------------------------
        # Tune explicit fire probability threshold
        # ----------------------------------------------------

        for threshold in np.arange(
            0.25,
            0.76,
            0.05,
        ):

            predicted = np.where(
                fire_probabilities
                >= threshold,

                "INDUSTRIAL_FIRE",

                "PERSISTENT_INDUSTRIAL_SOURCE",
            )

            macro_f1 = f1_score(
                actual,
                predicted,
                average="macro",
                zero_division=0,
            )

            balanced_accuracy = (
                balanced_accuracy_score(
                    actual,
                    predicted,
                )
            )

            fire_recall = recall_score(
                actual,
                predicted,
                pos_label=
                    "INDUSTRIAL_FIRE",
                zero_division=0,
            )

            fire_precision = (
                precision_score(
                    actual,
                    predicted,
                    pos_label=
                        "INDUSTRIAL_FIRE",
                    zero_division=0,
                )
            )

            fire_f1 = f1_score(
                actual,
                predicted,
                pos_label=
                    "INDUSTRIAL_FIRE",
                zero_division=0,
            )

            all_results.append(
                {
                    "feature_set":
                        feature_set_name,

                    "config":
                        config_number,

                    "max_depth":
                        params[
                            "max_depth"
                        ],

                    "min_samples_leaf":
                        params[
                            "min_samples_leaf"
                        ],

                    "class_weight":
                        str(
                            params[
                                "class_weight"
                            ]
                        ),

                    "threshold":
                        round(
                            float(
                                threshold
                            ),
                            2,
                        ),

                    "macro_f1":
                        round(
                            macro_f1,
                            4,
                        ),

                    "balanced_accuracy":
                        round(
                            balanced_accuracy,
                            4,
                        ),

                    "fire_precision":
                        round(
                            fire_precision,
                            4,
                        ),

                    "fire_recall":
                        round(
                            fire_recall,
                            4,
                        ),

                    "fire_f1":
                        round(
                            fire_f1,
                            4,
                        ),
                }
            )


results = pd.DataFrame(
    all_results
)

results = results.sort_values(
    by=[
        "macro_f1",
        "fire_recall",
        "fire_precision",
        "balanced_accuracy",
    ],
    ascending=False,
)


results.to_csv(
    OUTPUT_FILE,
    index=False,
)


print()
print("=" * 76)
print("TOP 15 CONFIGURATIONS")
print("=" * 76)

print(
    results
    .head(15)
    .to_string(
        index=False
    )
)


print()
print("=" * 76)
print("BEST WITH FIRE RECALL >= 0.80")
print("=" * 76)

high_recall = results[
    results[
        "fire_recall"
    ]
    >=
    0.80
]

if high_recall.empty:

    print(
        "No configuration reached "
        "80% fire recall."
    )

else:

    print(
        high_recall
        .head(10)
        .to_string(
            index=False
        )
    )


print()
print("=" * 76)
print("BEST OVERALL")
print("=" * 76)

print(
    results.iloc[0]
    .to_string()
)

print()
print(
    "Saved:"
)

print(
    OUTPUT_FILE
)
